# Generated by Django 3.2.9 on 2021-12-19 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_distributer', '0003_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2021, 12, 19)),
        ),
    ]
