# Generated by Django 3.2.9 on 2021-12-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_distributer', '0006_spending'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='spending',
            name='spend',
            field=models.IntegerField(),
        ),
    ]
